### ISSUE TITLE
`TypeError: Cannot read property 'trace' of undefined` when using browserify-shim

### ISSUE THREAD

**Issue by Swatinem** [Rich-Harris/sorcery#19]
So I’m using browserify-shim to pull in an external dependency from a cdn / browser global.
But when I do that, sorcery via gobble prints the following error:

```
TypeError: Cannot read property 'trace' of undefined
    at Node.trace (node_modules/gobble/node_modules/sorcery/dist/sorcery.js:715:20)
    at applySegment (node_modules/gobble/node_modules/sorcery/dist/sorcery.js:217:48)
    at Chain.apply (node_modules/gobble/node_modules/sorcery/dist/sorcery.js:264:5)
    at processWriteOptions (node_modules/gobble/node_modules/sorcery/dist/sorcery.js:29:18)
    at Chain.write (node_modules/gobble/node_modules/sorcery/dist/sorcery.js:304:30)
```

My browserify config (package.json) looks like this:

```json
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "gl-matrix": "global:window"
  }
```

**Comment by chirayuk** [comment]
I've been experiencing this intermittently for about 1 every 5-6 runs.

**Comment by mmilad** [comment]
any news on this task?
